export const FETCH_ACCOMMODATIONS = "FETCH_ACCOMMODATIONS"
export const FETCH_ACCOMMODATIONS_SUCCESS = "FETCH_ACCOMMODATIONS_SUCCESS"
export const FETCH_ACCOMMODATIONS_FAIL = "FETCH_ACCOMMODATIONS_FAIL"